<?php

/**
 * LRCODE
 * ============================================================================
 * 版权所有 2016-2030 江苏蓝儒网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.lanru.cn
 * ----------------------------------------------------------------------------
 * 这不是一个自由软件！您只能在不用于商业目的的前提下对程序代码进行修改和使用 .
 * 不允许对程序代码以任何形式任何目的的再发布。
 * ============================================================================
 * Author: 潇声
 * Date: 2019-12
 */

namespace app\admin\controller;

use app\common\controller\Backend;
use app\common\model\User;
use think\facade\App;
use think\facade\Hook;
use think\Validate;

class Index extends Backend
{
    protected $noNeedLogin = 'login';

    protected $noNeedRight = ['index', 'logout'];

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $allUser = User::count('id');
        $todayUser = User::where('addtime', '>=', strtotime(date('Y-m-d')))->count('id');
        $this->assign('version', App::version())
            ->assign('allUser', $allUser)->assign('todayUser', $todayUser)
            ->assign('allOrder', 1)->assign('allMoney', 10000);
        return $this->fetch();
    }

    public function login()
    {
        $url = $this->request->get('url', 'index/index');
        if ($this->auth->isLogin()) {
            $this->success('你已经存在，请不要重复登录', $url);
        }

        if ($this->request->isPost()) {
            $username = $this->request->post('username');
            $password = $this->request->post('password');
            $keeplogin = $this->request->post('keeplogin');

            $rule = [
                'username'  => 'require|length:3,30',
                'password'  => 'require|length:3,30',
            ];
            $data = [
                'username'  => $username,
                'password'  => $password,
            ];


            $validate = new Validate($rule, [], ['username' => '管理员名', 'password' => '密码']);
            $result = $validate->check($data);
            if (!$result) {
                $this->error($validate->getError(), $url);
            }

            $result = $this->auth->login($username, $password, $keeplogin ? 86400 : 0);
            if ($result === true) {
                Hook::listen("admin_login_after", $this->request);
                $this->success('登录成功', $url);
            } else {
                $msg = $this->auth->getError();
                $msg = $msg ? $msg : '用户名或密码不正确';
                $this->error($msg, $url);
            }

        }

        // 根据客户端的cookie,判断是否可以自动登录
        if ($this->auth->autologin()) {
            $this->redirect($url);
        }

        $this->view->engine->layout(false);
        return $this->fetch();
    }

    public function logout() {
        $this->auth->logout();
        $this->success('退出成功!', 'index/login');
    }
}