<?php

/**
 * LRCODE
 * ============================================================================
 * 版权所有 2016-2030 江苏蓝儒网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.lanru.cn
 * ----------------------------------------------------------------------------
 * 这不是一个自由软件！您只能在不用于商业目的的前提下对程序代码进行修改和使用 .
 * 不允许对程序代码以任何形式任何目的的再发布。
 * ============================================================================
 * Author: 潇声
 * Date: 2020-01
 */

namespace app\admin\controller\auth;


use app\admin\model\AdminGroup;
use app\common\controller\Backend;
use think\db\Where;

class Adminlog extends Backend
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->model = new \app\admin\model\AdminLog();

        $this->childrenAdminIds = $this->auth->getChildrenAdminIds(true);
        $this->childrenGroupIds = $this->auth->getChildrenGroupIds($this->auth->isSuperAdmin() ? true : false);

        $groupName = AdminGroup::where('id', 'in', $this->childrenGroupIds)
            ->column('id,name');

        $this->view->assign('groupdata', $groupName);
    }

    public function index()
    {
        $search = $this->request->post('search/a', []);

        $where = new Where();
        $where['admin_id'] = ['in', $this->childrenAdminIds];
        !empty($search['name']) and $where['name'] = ['like', '%' . $search['name'] .'%'];
        !empty($search['title']) and $where['title'] = ['like', '%' . $search['title'] .'%'];
        !empty($search['url']) and $where['url'] = ['like', '%' . $search['url'] .'%'];
        !empty($search['ip']) and $where['ip'] = ['like', '%' . $search['ip'] .'%'];

        $list = $this->model->where($where)->order("id", 'desc')->paginate(20);

        $this->assign('list', $list)->assign('search', $search);
        return $this->fetch();
    }

    public function detail()
    {
        $id = $this->request->param("id", 0, 'intval');
        $row = $this->model->find($id);
        if (!$row)
            $this->error('记录不存在');
        $this->assign("row", $row->toArray());
        return $this->fetch();
    }

}