<?php

/**
 * LRCODE
 * ============================================================================
 * 版权所有 2016-2030 江苏蓝儒网络科技有限公司，并保留所有权利。
 * 网站地址: http://www.lanru.cn
 * ----------------------------------------------------------------------------
 * 这不是一个自由软件！您只能在不用于商业目的的前提下对程序代码进行修改和使用 .
 * 不允许对程序代码以任何形式任何目的的再发布。
 * ============================================================================
 * Author: 潇声
 * Date: 2020-01
 */

namespace app\admin\controller\user;


use app\common\controller\Backend;
use app\common\model\UserRule;
use lanru\Tree;

class Rule extends Backend
{
    protected $rulelist;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new UserRule();

        $this->assign("statusList", $this->model->getStatusList());

        // 必须将结果集转换为数组
        $ruleList = collection($this->model->order('weight', 'desc')->select())->toArray();
        foreach ($ruleList as $k => &$v)
        {
            $v['title'] = $v['name'];
            $v['remark'] = $v['rule'];
        }
        unset($v);
        Tree::instance()->init($ruleList);
        $this->rulelist = Tree::instance()->getTreeList(Tree::instance()->getTreeArray(0), 'title');
        $ruledata = [0 => '无'];
        foreach ($this->rulelist as $k => &$v)
        {
            if (!$v['ismenu'])
                continue;
            $ruledata[$v['id']] = $v['title'];
        }
        $this->assign('ruledata', $ruledata);
    }

    public function index()
    {
        $this->assign('list', $this->rulelist);
        return $this->fetch();
    }

    /**
     * 删除
     */
    public function delete()
    {

        $id = $this->request->param('id');
        if (empty($id)) return $this->error('请选择删除的项目!');

        if (stripos($id, '~') !== false) $id = explode("~", $id);


        if ($id)
        {
            $delIds = [];
            if (is_array($id)) {
                foreach ($id as $k => $v) {
                    $delIds = array_merge($delIds, Tree::instance()->getChildrenIds($v, TRUE));
                }
            } else {
                $delIds = array_merge($delIds, Tree::instance()->getChildrenIds($id, TRUE));
            }
            $delIds = array_unique($delIds);
            $count = $this->model->where('id', 'in', $delIds)->delete();
            if ($count)
            {
                $this->success();
            }
        }
        $this->error();
    }
}